# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'sample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample
	pod 'OndatoSDK', '2.5.2'

end
